// Mock content for Badminton Pro Trainer.
// videoUrl points to a public-domain sample clip used only as a placeholder
// for the player UI — swap for real instructional footage later.
const PLACEHOLDER_VIDEO = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4";

const CATEGORIES = [
  {
    id: "fundamentals",
    name: "Fundamentals",
    emoji: "🏸",
    tagline: "For beginners building proper technique",
    gradient: "linear-gradient(135deg,#2b3350,#171b2b)",
    calPerMin: 6,
  },
  {
    id: "offensive",
    name: "Offensive Techniques",
    emoji: "⚡",
    tagline: "Improve attacking ability",
    gradient: "linear-gradient(135deg,#3a1f45,#1a1024)",
    calPerMin: 11,
  },
  {
    id: "defensive",
    name: "Defensive Techniques",
    emoji: "🛡",
    tagline: "Improve reaction and recovery",
    gradient: "linear-gradient(135deg,#123a3a,#0f1e24)",
    calPerMin: 9,
  },
  {
    id: "footwork",
    name: "Footwork & Movement",
    emoji: "🦶",
    tagline: "Improve speed and court coverage",
    gradient: "linear-gradient(135deg,#3a2a12,#241a0f)",
    calPerMin: 10,
  },
  {
    id: "netplay",
    name: "Net Play",
    emoji: "🎯",
    tagline: "Improve control around the net",
    gradient: "linear-gradient(135deg,#123245,#0f1c28)",
    calPerMin: 7,
  },
  {
    id: "strength",
    name: "Strength & Conditioning",
    emoji: "💪",
    tagline: "Badminton-specific athletic training",
    gradient: "linear-gradient(135deg,#3a1414,#241010)",
    calPerMin: 9,
  },
];

const EXERCISES = [
  // Fundamentals
  {
    id: "basic-grip",
    categoryId: "fundamentals",
    name: "Basic Grip Technique",
    difficulty: 1,
    goal: "Build a relaxed, adaptable grip that supports both forehand and backhand shots.",
    description: "The foundation of every badminton shot starts in the hand. This exercise trains the handshake grip and quick grip changes so your racket face arrives correctly for any shot.",
    coachingPoints: [
      "Hold the racket like shaking hands",
      "Keep a relaxed grip until the moment of impact",
      "Leave a small gap between palm and handle",
      "Practice switching forehand to backhand grip",
    ],
    commonMistakes: ["Squeezing the handle too tightly", "Using a frying-pan (flat) grip", "Fixed grip that never adjusts"],
    workout: { sets: 3, reps: 20, restSeconds: 30 },
  },
  {
    id: "forehand-clear",
    categoryId: "fundamentals",
    name: "Forehand Clear",
    difficulty: 2,
    goal: "Develop a full, high clear that pushes your opponent to the back court.",
    description: "The forehand clear is your reset shot. This drill builds the overhead swing path, timing, and follow-through needed to send the shuttle deep and high.",
    coachingPoints: [
      "Turn shoulders side-on before contact",
      "Reach up and contact the shuttle at full extension",
      "Snap the wrist through impact",
      "Follow through down and across the body",
    ],
    commonMistakes: ["Hitting with a bent arm", "No shoulder rotation", "Rushing the swing"],
    workout: { sets: 3, reps: 15, restSeconds: 45 },
  },
  {
    id: "backhand-clear",
    categoryId: "fundamentals",
    name: "Backhand Clear",
    difficulty: 3,
    goal: "Build a reliable backhand clear so your opponent can't attack your weak side.",
    description: "Improve your backhand consistency with a focus on the backhand grip, elbow lead, and forearm rotation that generates height and depth without arm strength alone.",
    coachingPoints: [
      "Switch to backhand grip early",
      "Lead the swing with the elbow",
      "Rotate the forearm through contact",
      "Keep the shuttle in front of your body",
    ],
    commonMistakes: ["Leading with the racket head instead of the elbow", "Late grip change", "Contacting the shuttle too low"],
    workout: { sets: 3, reps: 15, restSeconds: 45 },
  },
  {
    id: "serve-fundamentals",
    categoryId: "fundamentals",
    name: "Serve Fundamentals",
    difficulty: 1,
    goal: "Groove a consistent, legal low serve and a controlled high serve.",
    description: "A reliable serve sets up every rally. Practice both the low short serve for doubles and the high deep serve for singles with correct contact point and rules-compliant motion.",
    coachingPoints: [
      "Contact the shuttle below waist height",
      "Keep the racket head below the wrist at contact",
      "Use a gentle push for low serves",
      "Use full arm extension for high serves",
    ],
    commonMistakes: ["Contact point too high (fault)", "Telegraphing serve direction", "Inconsistent shuttle toss"],
    workout: { sets: 4, reps: 10, restSeconds: 30 },
  },
  {
    id: "ready-position",
    categoryId: "fundamentals",
    name: "Ready Position",
    difficulty: 1,
    goal: "Develop the balanced base stance that lets you react in any direction.",
    description: "Everything starts and ends in the ready position. This drill builds the athletic stance and center-court habit that makes fast footwork possible.",
    coachingPoints: [
      "Feet shoulder-width apart, knees slightly bent",
      "Weight on the balls of your feet",
      "Racket up in front of the body",
      "Return to center after every shot",
    ],
    commonMistakes: ["Standing flat-footed", "Racket resting too low", "Drifting away from center"],
    workout: { sets: 3, reps: 10, restSeconds: 20 },
  },
  {
    id: "basic-footwork",
    categoryId: "fundamentals",
    name: "Basic Footwork",
    difficulty: 2,
    goal: "Learn the core movement patterns to the four corners of the court.",
    description: "Efficient footwork saves energy and shortens reaction time. This session drills the fundamental step patterns to front, back, and side corners.",
    coachingPoints: [
      "Push off with the outside foot",
      "Take small adjustment steps, not one big lunge",
      "Keep your eyes on the shuttle, not your feet",
      "Return to base after each movement",
    ],
    commonMistakes: ["Crossing feet on direction changes", "Overstriding", "Standing upright while moving"],
    workout: { sets: 4, reps: 8, restSeconds: 30 },
  },

  // Offensive
  {
    id: "jump-smash",
    categoryId: "offensive",
    name: "Jump Smash Technique",
    difficulty: 4,
    goal: "Develop explosive attacking power and steep smash angles.",
    description: "The jump smash is one of badminton's most powerful offensive weapons. This exercise teaches proper timing, foot positioning, body rotation, and follow-through.",
    coachingPoints: [
      "Load weight onto back leg",
      "Use explosive leg drive",
      "Rotate hips and shoulders",
      "Contact shuttle at highest point",
      "Recover quickly after landing",
    ],
    commonMistakes: ["Jumping too early", "Using only arm strength", "Poor recovery position"],
    workout: { sets: 3, reps: 12, restSeconds: 60 },
  },
  {
    id: "power-smash",
    categoryId: "offensive",
    name: "Power Smash",
    difficulty: 4,
    goal: "Maximize racket head speed for a flat, penetrating smash.",
    description: "Build raw smash power from the ground up, linking leg drive, core rotation, and a fast forearm snap into one fluid motion.",
    coachingPoints: [
      "Generate power from the legs and core first",
      "Keep a high contact point",
      "Snap the wrist at the last moment",
      "Aim steep, not just hard",
    ],
    commonMistakes: ["Arm-only power", "Flat contact instead of downward angle", "Tensing up too early in the swing"],
    workout: { sets: 3, reps: 12, restSeconds: 60 },
  },
  {
    id: "half-smash",
    categoryId: "offensive",
    name: "Half Smash",
    difficulty: 3,
    goal: "Control smash placement and consistency by trading raw power for accuracy.",
    description: "The half smash keeps the shuttle fast but manageable, ideal for setting up net kills. Focus on disguise and precise placement over maximum power.",
    coachingPoints: [
      "Shorten the backswing slightly",
      "Keep the same disguise as a full smash",
      "Target the opponent's body or gaps",
      "Stay balanced through contact",
    ],
    commonMistakes: ["Telegraphing the softer shot", "Losing control chasing power", "Poor shuttle placement"],
    workout: { sets: 3, reps: 15, restSeconds: 45 },
  },
  {
    id: "drive-attacks",
    categoryId: "offensive",
    name: "Drive Attacks",
    difficulty: 3,
    goal: "Build flat, fast exchanges that pressure your opponent at mid-court.",
    description: "Drives keep the shuttle low and fast across the net, denying your opponent time to set up. This drill trains the compact, quick-reaction swing drives require.",
    coachingPoints: [
      "Use a short, compact swing",
      "Contact the shuttle early, in front of the body",
      "Keep the shuttle flat over the net",
      "Stay light on your feet between shots",
    ],
    commonMistakes: ["Backswing too long", "Hitting upward instead of flat", "Standing flat-footed during exchanges"],
    workout: { sets: 4, reps: 15, restSeconds: 40 },
  },
  {
    id: "fast-interceptions",
    categoryId: "offensive",
    name: "Fast Interceptions",
    difficulty: 4,
    goal: "Cut off the opponent's drives and lifts before they clear the net.",
    description: "Interceptions turn defense into instant offense. This drill sharpens reaction time and racket preparation to intercept the shuttle early at the net or mid-court.",
    coachingPoints: [
      "Anticipate from opponent's racket angle",
      "Keep the racket up and ready",
      "Take the shuttle as early as possible",
      "Punch, don't swing, on interceptions",
    ],
    commonMistakes: ["Reacting instead of anticipating", "Racket held too low", "Full swing instead of a short punch"],
    workout: { sets: 3, reps: 12, restSeconds: 45 },
  },
  {
    id: "attack-positioning",
    categoryId: "offensive",
    name: "Attack Positioning",
    difficulty: 3,
    goal: "Learn where to stand and move to keep constant offensive pressure.",
    description: "Winning the attack is as much about court position as shot power. This session builds the habit of closing the net after an attacking shot to finish the point.",
    coachingPoints: [
      "Follow your smash toward the net",
      "Split-step before every opponent shot",
      "Cover the straight return first",
      "Stay balanced, not overcommitted",
    ],
    commonMistakes: ["Standing flat-footed after attacking", "Overcommitting to one side", "Not following the shot forward"],
    workout: { sets: 3, reps: 10, restSeconds: 40 },
  },

  // Defensive
  {
    id: "defensive-blocks",
    categoryId: "defensive",
    name: "Defensive Blocks",
    difficulty: 3,
    goal: "Absorb pace and redirect smashes into tight net returns.",
    description: "Blocking converts an opponent's power against them. This drill trains a soft, controlled racket face to place blocks tight to the net under pressure.",
    coachingPoints: [
      "Keep the grip relaxed to absorb pace",
      "Angle the racket face downward",
      "Meet the shuttle early, in front of the body",
      "Aim for tight to the net, not deep",
    ],
    commonMistakes: ["Gripping too tight and popping the shuttle up", "Reacting late", "Blocking too deep, inviting another attack"],
    workout: { sets: 3, reps: 15, restSeconds: 40 },
  },
  {
    id: "smash-defense",
    categoryId: "defensive",
    name: "Smash Defense",
    difficulty: 4,
    goal: "React quickly and return smashes with control instead of panic.",
    description: "Facing a smash tests reflexes and positioning. This drill builds the low, ready base and quick racket preparation needed to defend consistently.",
    coachingPoints: [
      "Stay low with knees bent",
      "Keep racket up and centered",
      "Track the shuttle, not the opponent's swing",
      "Use a short, controlled block or lift",
    ],
    commonMistakes: ["Standing too upright", "Guessing direction early", "Overswinging on the return"],
    workout: { sets: 3, reps: 12, restSeconds: 50 },
  },
  {
    id: "drive-defense",
    categoryId: "defensive",
    name: "Drive Defense",
    difficulty: 3,
    goal: "Handle fast flat exchanges without losing shuttle control.",
    description: "Drive defense is about quick hands and a stable base. This drill trains rapid-fire returns to flat, fast shuttle exchanges at mid-court.",
    coachingPoints: [
      "Keep elbows slightly bent and ready",
      "Use wrist and forearm for quick returns",
      "Stay on the balls of your feet",
      "Return flat, not lifted, when possible",
    ],
    commonMistakes: ["Reaching with a straight arm", "Flat-footed stance", "Popping the shuttle up under pressure"],
    workout: { sets: 4, reps: 15, restSeconds: 35 },
  },
  {
    id: "lift-technique",
    categoryId: "defensive",
    name: "Lift Technique",
    difficulty: 2,
    goal: "Buy time under pressure with a controlled, high defensive lift.",
    description: "When under attack, a good lift resets the rally. This drill builds a low-to-high swing path that sends the shuttle deep with minimal setup time.",
    coachingPoints: [
      "Bend knees to get under the shuttle",
      "Use legs to drive the lift, not just the arm",
      "Follow through high and toward the back court",
      "Recover to base immediately after",
    ],
    commonMistakes: ["Lifting with arm only", "Shuttle not reaching the back court", "Slow recovery after the lift"],
    workout: { sets: 3, reps: 15, restSeconds: 35 },
  },
  {
    id: "counter-attacking",
    categoryId: "defensive",
    name: "Counter Attacking",
    difficulty: 4,
    goal: "Turn a defensive return into your own attacking opportunity.",
    description: "The best defenders are also counter-attackers. This drill trains converting a block or lift return into an immediate offensive follow-up.",
    coachingPoints: [
      "Defend with an attacking mindset",
      "Watch for a weak reply to pounce on",
      "Move forward immediately after defending",
      "Stay balanced to transition quickly",
    ],
    commonMistakes: ["Purely passive defending", "Slow transition back to attack", "Losing balance while defending"],
    workout: { sets: 3, reps: 10, restSeconds: 45 },
  },

  // Footwork & Movement
  {
    id: "six-point-footwork",
    categoryId: "footwork",
    name: "Six-Point Footwork Drill",
    difficulty: 3,
    goal: "Cover all six corners of the court with efficient, repeatable steps.",
    description: "The classic six-point drill builds full-court movement patterns, combining lunges, chasse steps, and quick recovery to base.",
    coachingPoints: [
      "Explode out of the ready position",
      "Use the correct step pattern for each corner",
      "Touch each corner with a lunge, not a jog",
      "Sprint back to center every time",
    ],
    commonMistakes: ["Jogging instead of explosive steps", "Skipping the return to base", "Wrong footwork pattern for the corner"],
    workout: { sets: 4, reps: 6, restSeconds: 45 },
  },
  {
    id: "split-step-training",
    categoryId: "footwork",
    name: "Split-Step Training",
    difficulty: 2,
    goal: "Time your split-step to react a fraction of a second faster.",
    description: "The split-step loads your legs right as your opponent contacts the shuttle, letting you push off explosively in any direction.",
    coachingPoints: [
      "Time the hop to the opponent's contact moment",
      "Land with feet shoulder-width, knees soft",
      "Stay light — this is a hop, not a jump",
      "Push off immediately in the needed direction",
    ],
    commonMistakes: ["Split-stepping too early or late", "Landing flat-footed and stiff", "Jumping too high, losing reaction time"],
    workout: { sets: 4, reps: 12, restSeconds: 30 },
  },
  {
    id: "explosive-movement",
    categoryId: "footwork",
    name: "Explosive Movement Drills",
    difficulty: 4,
    goal: "Build first-step speed and acceleration around the court.",
    description: "Short, sharp accelerations translate directly into reaching shots faster. This session uses cone and shadow drills to build explosive first steps.",
    coachingPoints: [
      "Drive off the front foot explosively",
      "Keep the first two steps short and fast",
      "Stay low through the acceleration phase",
      "Reset fully between reps for quality",
    ],
    commonMistakes: ["Standing too tall on the first step", "Long first stride instead of short and fast", "Rushing reps without full recovery"],
    workout: { sets: 5, reps: 8, restSeconds: 40 },
  },
  {
    id: "recovery-positioning",
    categoryId: "footwork",
    name: "Recovery Positioning",
    difficulty: 2,
    goal: "Get back to base quickly and in balance after every shot.",
    description: "Fast recovery is what makes consecutive shots possible. This drill builds the habit of shuffling back to center immediately after reaching a corner.",
    coachingPoints: [
      "Push off the corner immediately after the shot",
      "Use chasse steps to return, not a jog",
      "Arrive at base balanced, not off-stride",
      "Reset racket to ready position while moving",
    ],
    commonMistakes: ["Pausing to admire the shot", "Turning your back on the court while recovering", "Arriving off-balance"],
    workout: { sets: 4, reps: 10, restSeconds: 35 },
  },
  {
    id: "direction-change",
    categoryId: "footwork",
    name: "Direction Change Drills",
    difficulty: 3,
    goal: "Change direction sharply without losing speed or balance.",
    description: "Badminton rallies demand constant direction changes. This drill trains sharp cuts and decelerations that keep you fast and under control.",
    coachingPoints: [
      "Bend the knees to lower your center of gravity",
      "Plant the outside foot to change direction",
      "Keep steps short during the transition",
      "Accelerate immediately out of the change",
    ],
    commonMistakes: ["Standing too upright through the cut", "Crossing feet during the change", "Losing speed on the exit"],
    workout: { sets: 4, reps: 10, restSeconds: 35 },
  },

  // Net Play
  {
    id: "net-kill",
    categoryId: "netplay",
    name: "Net Kill",
    difficulty: 3,
    goal: "Finish rallies at the net with a sharp, downward kill shot.",
    description: "A net kill ends the point when your opponent gives you a high shuttle at the net. This drill builds the quick, compact swing needed to punch it away.",
    coachingPoints: [
      "Get to the shuttle early, before it drops",
      "Use a short punching motion, not a full swing",
      "Angle the shot steeply downward",
      "Stay balanced on the approach",
    ],
    commonMistakes: ["Waiting too long and letting the shuttle drop", "Overswinging into the net", "Hitting flat instead of steep"],
    workout: { sets: 3, reps: 15, restSeconds: 35 },
  },
  {
    id: "net-drop",
    categoryId: "netplay",
    name: "Net Drop",
    difficulty: 2,
    goal: "Place a soft, tight shot just over the net to pressure your opponent.",
    description: "The net drop is a finesse shot that dies close to the net. This drill focuses on soft hands and precise racket face control.",
    coachingPoints: [
      "Use a soft, relaxed grip on contact",
      "Contact the shuttle out in front",
      "Guide, don't hit — minimal swing",
      "Aim to clear the net by inches, not feet",
    ],
    commonMistakes: ["Too much swing power", "Contacting the shuttle too late", "Shot lands too far from the net"],
    workout: { sets: 3, reps: 15, restSeconds: 30 },
  },
  {
    id: "spinning-net-shot",
    categoryId: "netplay",
    name: "Spinning Net Shot",
    difficulty: 4,
    goal: "Add spin to net shots to make them harder to read and return.",
    description: "A spinning net shot tumbles the shuttle over the net, disguising direction and making returns difficult. This drill trains the subtle wrist and racket face motion needed.",
    coachingPoints: [
      "Use a slicing racket face motion",
      "Brush across the shuttle, don't push it",
      "Keep the motion small and disguised",
      "Practice both slice directions",
    ],
    commonMistakes: ["Motion too large, easy to read", "Not enough slice to create tumble", "Inconsistent contact point"],
    workout: { sets: 3, reps: 12, restSeconds: 40 },
  },
  {
    id: "net-recovery",
    categoryId: "netplay",
    name: "Net Recovery",
    difficulty: 2,
    goal: "Move to and from the net efficiently without wasting steps.",
    description: "Getting in and out of the net area quickly keeps you ready for the next shot. This drill trains the lunge-and-recover pattern specific to net exchanges.",
    coachingPoints: [
      "Lunge forward with the racket leg",
      "Keep your back straight through the lunge",
      "Push back off the front foot to recover",
      "Return to base facing the court",
    ],
    commonMistakes: ["Overextending the lunge", "Standing up slowly after the shot", "Turning away from the court while recovering"],
    workout: { sets: 4, reps: 10, restSeconds: 30 },
  },
  {
    id: "tumble-technique",
    categoryId: "netplay",
    name: "Tumble Technique",
    difficulty: 4,
    goal: "Master the tumbling net shot that disguises shuttle direction.",
    description: "The tumble shot flips the shuttle over the net so the opponent can't read its path early. This advanced drill isolates the wrist action that creates the tumble.",
    coachingPoints: [
      "Use a light touch under the shuttle base",
      "Add a small wrist flick at contact",
      "Keep the racket face open through contact",
      "Disguise the shot until the last moment",
    ],
    commonMistakes: ["Too much force, shuttle flies instead of tumbles", "Telegraphing the shot early", "Inconsistent wrist timing"],
    workout: { sets: 3, reps: 12, restSeconds: 40 },
  },

  // Strength & Conditioning
  {
    id: "explosive-leg-training",
    categoryId: "strength",
    name: "Explosive Leg Training",
    difficulty: 3,
    goal: "Build the leg power behind jumps, lunges, and fast direction changes.",
    description: "Badminton-specific leg power comes from plyometric and lunge-based training. This session builds explosive strength that transfers directly to court movement.",
    coachingPoints: [
      "Focus on explosive concentric movement",
      "Land softly to protect the joints",
      "Keep the core braced throughout",
      "Prioritize quality over quantity of reps",
    ],
    commonMistakes: ["Landing stiff-legged", "Rushing through reps", "Skipping the warm-up before explosive work"],
    workout: { sets: 4, reps: 12, restSeconds: 60 },
  },
  {
    id: "core-stability",
    categoryId: "strength",
    name: "Core Stability",
    difficulty: 2,
    goal: "Build the rotational core strength that powers every stroke.",
    description: "A strong, stable core links your legs to your racket arm. This session trains anti-rotation and rotational core strength for more powerful, controlled strokes.",
    coachingPoints: [
      "Keep the spine neutral during holds",
      "Breathe steadily, don't hold your breath",
      "Engage the core before each rep",
      "Move with control, not momentum",
    ],
    commonMistakes: ["Arching the lower back", "Rushing through reps with momentum", "Holding breath during isometric holds"],
    workout: { sets: 3, reps: 15, restSeconds: 30 },
  },
  {
    id: "shoulder-strengthening",
    categoryId: "strength",
    name: "Shoulder Strengthening",
    difficulty: 2,
    goal: "Build shoulder strength and stability to protect against overuse injury.",
    description: "Repeated overhead strokes put stress on the shoulder. This session strengthens the rotator cuff and stabilizing muscles to support power and prevent injury.",
    coachingPoints: [
      "Use light resistance and controlled tempo",
      "Keep shoulder blades stable throughout",
      "Avoid shrugging during overhead movement",
      "Stop if you feel joint pain, not just fatigue",
    ],
    commonMistakes: ["Using too much resistance too soon", "Shrugging shoulders during presses", "Rushing the tempo"],
    workout: { sets: 3, reps: 15, restSeconds: 30 },
  },
  {
    id: "agility-drills",
    categoryId: "strength",
    name: "Agility Drills",
    difficulty: 3,
    goal: "Sharpen coordination and reaction speed for faster court coverage.",
    description: "Ladder and cone drills build the coordination and quick-feet patterns that make badminton footwork sharper and more automatic.",
    coachingPoints: [
      "Stay light on your feet throughout",
      "Keep your eyes up, not looking at your feet",
      "Prioritize precise foot placement over speed",
      "Increase speed only once the pattern is clean",
    ],
    commonMistakes: ["Rushing before the pattern is clean", "Looking down at the feet", "Heavy, flat-footed steps"],
    workout: { sets: 4, reps: 10, restSeconds: 30 },
  },
  {
    id: "endurance-workouts",
    categoryId: "strength",
    name: "Endurance Workouts",
    difficulty: 3,
    goal: "Build the aerobic and anaerobic capacity to sustain intensity through a full match.",
    description: "Long rallies and multi-game matches demand a strong engine. This session mixes interval and steady-state work tailored to badminton's stop-start intensity.",
    coachingPoints: [
      "Match interval intensity to rally intensity",
      "Keep rest periods consistent",
      "Focus on quick recovery between intervals",
      "Build volume gradually week to week",
    ],
    commonMistakes: ["Going too hard too early in a session", "Inconsistent rest periods", "Ignoring recovery and hydration"],
    workout: { sets: 5, reps: 1, restSeconds: 60 },
  },
];

function getCategory(id) {
  return CATEGORIES.find((c) => c.id === id);
}

function getExercise(id) {
  return EXERCISES.find((e) => e.id === id);
}

function getExercisesForCategory(categoryId) {
  return EXERCISES.filter((e) => e.categoryId === categoryId);
}
